apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-hub-openshift
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: tenant-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: tenants
      source:
        repoURL: https://github.com/eformat/etx-agentic-ai.git
        path: infra/tenants/acme-co/base/sno
        plugin:
          name: argocd-novault-plugin-kustomize
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
